[package]
name = "pam"
edition.workspace = true
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "pam"
path = "src/lib.rs"
doc = false

[dependencies]
libc.workspace = true