[package]
name = "xtask-test-integration"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
cli-xtask.workspace = true
xshell.workspace = true
anyhow.workspace = true

[lints]
workspace = true