[workspace]
members = ["xtask"]

[package]
name = "pam-authramp"
version = "0.1.0"
description = "A PAM module for implementing ramping up delay on authentication failures."
authors = ["34n0 <34n0@immerda.ch>"]
license = "GPL-3.0"
publish = false
edition = "2021"

[lib]
name = "pam_authramp"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.31"
dotenv_codegen = "0.15.0"
once_cell = "1.19.0"
pam-bindings = "0.1.1"
pam-client = "0.5.0"
sysinfo = "0.30.0"
syslog = "6.1.0"
tempdir = "0.3.7"
tempfile = "3.8.1"
users = "0.11.0"
log = "0.4"
toml = "0.8.8"
