[package]
name = "pam-authramp"
version = "0.3.0"
description = "The AuthRamp PAM module provides an account lockout mechanism based on the number of authentication failures."
authors = ["34n0 <34n0@immerda.ch>"]
license = "GPL-3.0"
edition = "2021"

[workspace]
members = ["crates/lib", "crates/xtask"]
default-members = ["crates/lib"]

[dev-dependencies]
pam-client = "0.5.0"
dotenv_codegen = "0.15.0"
tempfile = "3.8.1"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/libpam_authramp.so", dest = "/usr/lib64/security/libpam_authramp.so", mode = "755" },
    { source = "examples/system-auth/authramp.conf", dest = "/etc/security/authramp.conf", mode = "644" },
]

[package.metadata.deb]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/libpam_authramp.so", "usr/lib64/security/", "755"],
    ["examples/system-auth/authramp.conf", "/etc/security/authramp.conf", "644"],
]