name: Clippy check

on:
  workflow_dispatch:
  pull_request:

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Rustup add Clippy
        run: rustup component add clippy
      
      - name: Run linter
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          args: --all-features