[package]
name = "xtask-integration-test"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
cli-xtask.workspace = true
xshell.workspace = true

[lints]
workspace = true