[package]
name = "xtask"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
cli-xtask = { version = "0.8.0", features = ["main", "lib-crate"] }
xshell = "0.2.5"
