on:
  pull_request:
  workflow_dispatch:
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libpam-dev clang libclang-dev
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-features
