on:
  pull_request:
  workflow_dispatch:
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: 17.0
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
